name: RandomTPPlugin
main: com.example.randomtp.RandomTPPlugin
version: 1.0
api-version: 1.21
folia-supported: true
commands:
  randomtp:
    description: ワールドボーダー内のランダムな場所にテレポートします。
    usage: /randomtp